server:
  servlet:
    context-path: /
  port: 9963

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个
      driver-class-name: org.gjt.mm.mysql.Driver       #配置MySQL的驱动程序类
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
      username: root
      password: abc123
      filters: stat,wall,log4j     #druid监控配置
      dbcp2:
      　min-idle: 5         #数据库连接池的最小维持连接数
      　initial-size: 5     #初始化提供的连接数
      　max-total: 5          #最大的连接数
        max-wait-millis: 200        #等待连接获取的最大超时时间



  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    enabled: true
  # 热加载
  #devtools:
    #restart:
      #热部署生效
    #  enabled: true
    #  #设置重启的目录，添加那个目录的文件需要restart
   #   additional-paths: src/main/java
  #    #排除那个目录的文件不需要restart
    #  additional-exclude: static/**,public/**
  #    #classpath目录下的WEB-INF文件夹内容修改不重启
  #    exclude: com

##############  mybatis-plus #############
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com。stuil.**.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    ## 日志 ##
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache
